# Banco de dados
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:15432/everafter
spring.datasource.username=danssaugustus
spring.datasource.password=259168

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Banco de dados
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.url=${URL_DATABASE}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}